services:
  - type: web
    name: signalr-global-chat
    runtime: docker
    plan: free
    region: frankfurt
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: DOTNET_HOSTBUILDER__RELOADCONFIGONCHANGE
        value: "false"
      - key: DOTNET_USE_POLLING_FILE_WATCHER
        value: "true"
